function check_microstim_cerestim_mit_cable
%Written by Xing 28/9/17
%Connect modified blue MIT cable to CereStim, bank A (chs 1-32). End of
%modified cable connects to circuit board with a 100-kOhm resistor for each
%channel, i.e. 200 kOhm for connection that spans a neural channel and the
%ground. Test sending of microstimulation pulses with
%runstim_microstim_test_waveform2.m, runstim_microstim_saccade_catch19.m, 
%and runstim_microstim_saccade_catch22_test_wait.m. Measure voltage across resistors
%using oscilloscope, and send output to NSP analog input 14. Perform short 
%recordings and check signal. Vary timing of pulse trains, check timing of
%pulse onset relative to sending of trigger (dasbit sends MicroB), as well
%as to timing of sync pulse generated by sync pulse output port on
%CereStim (>3V is considered 'high'). 
%Find that pulse train onset is slightly variable (7-9 ms) when no 'wait'
%command is used. When stimulator.wait(1.65) used (add a temporal delay of
%1.65 ms before sending of train), stimulation onset is delayed by 24 ms.
%When stimulator.wait(10) used (add a temporal delay of 10 ms before
%sending of train), stimulation onset is delayed by 32 ms.

date='280917_test_microstim_waveform';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
eyeChannels=142;%analog input 14
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
eyeDataMat=['D:\data\',date,'\',instanceName,'_NSch_eye_channels.mat'];
for channelInd=1:length(eyeChannels)
    readChannel=['c:',num2str(eyeChannels(channelInd)),':',num2str(eyeChannels(channelInd))];
    NSchOriginal=openNSx(instanceNS6FileName);
    NSch{channelInd}=NSchOriginal.Data;
end

%test bipolar stimulation, also record 5-volt reference signal to estimate
%amplitude
date='280917_test_microstim_waveform4';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
eyeChannels=142:144;%analog input 14 to 16
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:));
hold on;plot(NSch(2,:),'r');
plot(NSch(3,:),'g');

%test second electrode, temporal delay of 1.65 ms for start of train
date='280917_test_microstim_waveform6';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
eyeChannels=142;%analog input 14 to 16
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:));
ylimits=get(gca,'ylim');
plot([139026 139026],ylimits,'k:');

%test second electrode, temporal delay of 10 ms for start of train
date='280917_test_microstim_waveform7';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
eyeChannels=142;%analog input 14 to 16
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:));
ylimits=get(gca,'ylim');
plot([20249 20249],ylimits,'k:');
plot([93099 93099],ylimits,'k:');
plot([165681 165681],ylimits,'k:');

%test first electrode, no temporal delay for start of train
date='280917_test_microstim_waveform8';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
eyeChannels=142;%analog input 14 to 16
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:));
ylimits=get(gca,'ylim');
stimBTimestamps=[1 9 17 25];
for i=1:length(stimBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(stimBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(stimBTimestamps(i))],ylimits,'r:');
end

%test second electrode, no temporal delay for start of train
date='280917_test_microstim_waveform9';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
eyeChannels=142;%analog input 14 to 16
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:));
ylimits=get(gca,'ylim');
StimB=1;
stimBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^StimB);
for i=1:length(stimBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(stimBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(stimBTimestamps(i))],ylimits,'r:');
end
%get cursor x coordinates manually
(cursor_info2.Position(1) - cursor_info1.Position(1))/30000

%test first electrode, check sync pulses on analog inputs 1 and 12 (14295
%and 14293, respectively)
date='280917_test_microstim_waveform10';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14275)
plot(NSch(1,:));
ylimits=get(gca,'ylim');
StimB=1;
stimBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^StimB);
for i=1:length(stimBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(stimBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(stimBTimestamps(i))],ylimits,'r:');
end
%get cursor x coordinates manually
(cursor_info2.Position(1) - cursor_info1.Position(1))/30000
%analog input 12 (Cerestim 14293)
plot(NSch(12,:),'m');
%analog input 14 (electrode 1)
plot(NSch(14,:),'c');

%test second electrode, check sync pulses on analog inputs 1 and 12 (14295
%and 14293, respectively)
date='280917_test_microstim_waveform11';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14275)
plot(NSch(1,:));
ylimits=get(gca,'ylim');
StimB=1;
stimBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^StimB);
for i=1:length(stimBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(stimBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(stimBTimestamps(i))],ylimits,'r:');
end
%get cursor x coordinates manually
(cursor_info2.Position(1) - cursor_info1.Position(1))/30000
%analog input 12 (Cerestim 14293)
plot(NSch(12,:),'m');
%analog input 14 (electrode 1)
plot(NSch(14,:),'c');

%test electrode, check timing of trigger pulse on analog input 16 and
%stimulation waveform on electrode 1, analog input 1 (14293)
%Delivered current at 20 uA, and resistor has impedance of ~40-50 kOhms.
%Hence expected voltage in each phase is 0.8V, matches amplitude of each
%phase in recorded data (around 0.7V).
date='290917_test_microstim_waveform1';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14275)
plot(NSch(1,:),'b');
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
plot(NSch(16,:),'m');%plot signal on analog input 16, which measures 4.6V in the current recording

%Delivered current at 100 uA, and resistor has impedance of ~40-50 kOhms,
%but circuit is modified such that the current flows across two resistors
%instead of one, thereby halving the voltage recorded (or effectively
%halving the resistance). Did this to avoid saturation of the NSP recording
%system, allowing us to measure amplitude of waveform for delivery of higher currents.
%Amplitude of individual phase is ~2.3V, expected amplitude is around 2.5V
%(100 uA x 23.2 kOhms = 2.3V).
date='290917_test_microstim_waveform2';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14275)
plot(NSch(1,:),'b');
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
plot(NSch(16,:),'m');%plot signal on analog input 16, which measures 4.6V in the current recording
ylimits=get(gca,'ylim');
amplitudeOnePhase=(ylimits(2)-ylimits(1))/2%12605 data points
ylimits=get(gca,'ylim');
amplitudeRef=ylimits(2)-ylimits(1)%25210 data points
4.6/25210*12605%2.3V

%Delivered current at 200 uA, and resistor has impedance of ~40-50 kOhms,
%but circuit is modified such that the current flows across two resistors
%instead of one, thereby halving the voltage recorded (or effectively
%halving the resistance). Did this to avoid saturation of the NSP recording
%system, allowing us to measure amplitude of waveform for delivery of higher currents.
%Amplitude of individual phase is , expected amplitude is around 2.5V
%(200 uA x 23.2 kOhms = 4.6V).
date='290917_test_microstim_waveform3';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14275)
plot(NSch(1,:),'b');
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
plot(NSch(16,:),'m');%plot signal on analog input 16, which measures 4.6V in the current recording
amplitudeOnePhase=(max(double(NSch(1,:)))-min(double(NSch(1,:))))/2%16384 data points
amplitudeRef=max(double(NSch(16,:)))-min(double(NSch(16,:)))%31056 data points
4.6*amplitudeOnePhase/amplitudeRef%3.7V

%Used wait(10) to add 10-ms temporal delay to train of pulses on second CereStim.
%Delivered current at two different amplitudes, and resistor has impedance of ~40-50 kOhms,
%but circuit is modified such that the current flows across two resistors
%instead of one, thereby halving the voltage recorded (or effectively
%halving the resistance). 
date='290917_test_microstim_waveform4';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14273)
plot(NSch(1,:),'b');
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
plot(NSch(16,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
(cursor_info1.Position(1) - cursor_info2.Position(1))/30000

%Used wait(0) to add 0-ms temporal delay to train of pulses on second CereStim.
%Delivered current at two different amplitudes, and resistor has impedance of ~40-50 kOhms,
%but circuit is modified such that the current flows across two resistors
%instead of one, thereby halving the voltage recorded (or effectively
%halving the resistance). Also recorded sync pulse output from 14293, on
%analog input 12.
date='290917_test_microstim_waveform5';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14273)
plot(NSch(1,:),'b');
plot(NSch(16,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
plot(NSch(12,:),'c');%plot signal on analog input 12, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
%pulse is sent 20 ms after trigger, i.e. wait(0) results in delay of 20 ms.

%Used wait(10) to add 10-ms temporal delay to train of pulses on second CereStim.
%Delivered current at two different amplitudes, and resistor has impedance of ~40-50 kOhms,
%but circuit is modified such that the current flows across two resistors
%instead of one, thereby halving the voltage recorded (or effectively
%halving the resistance). Also recorded sync pulse output from 14293, on
%analog input 12.
date='290917_test_microstim_waveform6';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14273)
plot(NSch(1,:),'b');
plot(NSch(16,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(12,:),'c');%plot signal on analog input 12, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 30 ms after trigger, i.e. wait(10) results in delay of 30 ms.

%Used wait(20) to add 20-ms temporal delay to train of pulses on second CereStim.
%Delivered current at two different amplitudes, and resistor has impedance of ~40-50 kOhms,
%but circuit is modified such that the current flows across two resistors
%instead of one, thereby halving the voltage recorded (or effectively
%halving the resistance). Also recorded sync pulse output from 14293, on
%analog input 12.
date='290917_test_microstim_waveform7';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14273)
plot(NSch(1,:),'b');
plot(NSch(16,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(12,:),'c');%plot signal on analog input 12, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 20 ms after trigger, i.e. wait(20) results in delay of 20 ms.

%Used wait(50) to add 50-ms temporal delay to train of pulses on second CereStim.
%Delivered current at two different amplitudes, and resistor has impedance of ~40-50 kOhms,
%but circuit is modified such that the current flows across two resistors
%instead of one, thereby halving the voltage recorded (or effectively
%halving the resistance). Also recorded sync pulse output from 14293, on
%analog input 12.
date='290917_test_microstim_waveform8';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14273)
plot(NSch(1,:),'b');
plot(NSch(16,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(12,:),'c');%plot signal on analog input 12, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 54 ms after trigger, i.e. wait(50) results in delay of 54 ms.

%Used wait(100) to add 100-ms temporal delay to train of pulses on second CereStim.
%Delivered current at two different amplitudes, and resistor has impedance of ~40-50 kOhms,
%but circuit is modified such that the current flows across two resistors
%instead of one, thereby halving the voltage recorded (or effectively
%halving the resistance). Also recorded sync pulse output from 14293, on
%analog input 12.
date='290917_test_microstim_waveform9';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14273)
plot(NSch(1,:),'b');
plot(NSch(16,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(12,:),'c');%plot signal on analog input 12, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 116 ms after trigger, i.e. wait(100) results in delay of 116 ms.

%Used wait(100) to add 100-ms temporal delay to train of pulses on second CereStim.
%Recorded sync pulse output from 14293, on
%analog input 13.
date='031017_test_microstim_waveform1';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14273)
plot(NSch(129,:),'b');
plot(NSch(144,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(141,:),'c');%plot signal on analog input 12, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 116 ms after trigger, i.e. wait(100) results in delay of 116 ms.

%Used wait(0) to add 0-ms temporal delay to train of pulses on second CereStim.
%Recorded sync pulse output from 14293, on
%analog input 13.
date='031017_test_microstim_waveform2';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14273)
plot(NSch(129,:),'b');
plot(NSch(144,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(141,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 20 ms after trigger, i.e. wait(0) results in delay of 20 ms.

%Used Stim Manager to send pulse on CereStim 14293.
%Recorded sync pulse output from 14293, on
%analog input 13.
date='031017_test_microstim_waveform4';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14273)
plot(NSch(129,:),'b');
plot(NSch(144,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(141,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent immediately after trigger, i.e. when Stim Manager used, no
%delay occurs when when wait command is not used.

%Used Stim Manager to send pulse on CereStim 14293. Wait(0).
%Recorded sync pulse output from 14293, on
%analog input 13.
date='031017_test_microstim_waveform5';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14273)
plot(NSch(129,:),'b');
plot(NSch(144,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(141,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 16 ms after trigger, i.e. wait(0) results in delay of 16 ms when Stim Manager is used.

%Used Stim Manager to send pulse on CereStim 14293. Wait(100).
%Recorded sync pulse output from 14293, on
%analog input 13.
date='031017_test_microstim_waveform6';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14273)
plot(NSch(129,:),'b');
plot(NSch(144,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(141,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
(cursor_info3.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 116 ms after trigger, i.e. wait(100) results in delay of 116 ms when Stim Manager is used.

%Used Stim Manager to send pulse on CereStim 14293. Wait(20).
%Recorded sync pulse output from 14293, on
%analog input 13.
date='031017_test_microstim_waveform7';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
%analog input 1 (Cerestim 14273)
plot(NSch(129,:),'b');
plot(NSch(144,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(141,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
(cursor_info3.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 20 ms after trigger, i.e. wait(20) results in delay of 20 ms when Stim Manager is used.

%Used Matlab code to send pulse on CereStim 14293. No wait() command used.
%Recorded sync pulse output from 14293, on
%analog input 13.
date='031017_test_microstim_waveform8';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(129,:),'b');
plot(NSch(144,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(141,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent immediately after trigger, i.e. no wait() results in no delay of 20 ms when Matlab script is used.

%Used Matlab code to send pulse on CereStim 14293. Wait(0) command used.
%Recorded sync pulse output from 14293, on
%analog input 13.
date='031017_test_microstim_waveform9';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(129,:),'b');
plot(NSch(144,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(141,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 20 ms after trigger, i.e. wait(0) results in delay of 20 ms when Matlab code is used.

%Used Matlab code to send pulse on CereStim 14177 (the CereStim that was
%sent back to BR and that Saman reprogrammed). No wait() command used. 
%Recorded sync pulse output from 14177, on analog input 13.
date='041017_test_microstim_waveform1';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:),'b');
plot(NSch(16,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(13,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=65344;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent immediately after trigger, i.e. when CereStim 14177 is used and no wait() function present, the stimulation occurs with a slight delay of 100 us.

%Used Matlab code to send pulse on CereStim 14177 (the CereStim that was
%sent back to BR and that Saman reprogrammed). Wait(0) command used. 
%Recorded sync pulse output from 14177, on analog input 13.
date='041017_test_microstim_waveform2';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:),'b');
plot(NSch(16,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(13,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=65344;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 0.1 ms after trigger, i.e. when CereStim 14177 is used and wait(0) function present, the stimulation occurs very quickly, with a slight delay of 100 us.

%Used Matlab code to send pulse on CereStim 14177 (the CereStim that was
%sent back to BR and that Saman reprogrammed). Wait(10) command used. 
%Recorded sync pulse output from 14177, on analog input 13.
date='041017_test_microstim_waveform3';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:),'b');
plot(NSch(16,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(13,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=65344;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 10.1 ms after trigger, i.e. when CereStim 14177 is used and wait(10) function present, the stimulation occurs at correct time, with a slight delay of 100 us.

%Used Matlab code to send pulse on CereStim 14177 (the CereStim that was
%sent back to BR and that Saman reprogrammed). Wait(50) command used. 
%Recorded sync pulse output from 14177, on analog input 13.
date='041017_test_microstim_waveform4';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:),'b');
plot(NSch(16,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(13,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=65344;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 50.2 ms after trigger, i.e. when CereStim 14177 is used and wait(50) function present, the stimulation occurs at correct time, with a slight delay of 200 us.

%Used Matlab code to send pulse on CereStim 14177 (the CereStim that was
%sent back to BR and that Saman reprogrammed). Wait(100) command used. 
%Recorded sync pulse output from 14177, on analog input 13.
date='041017_test_microstim_waveform5';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:),'b');
plot(NSch(16,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(13,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=65344;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%pulse is sent 100.3 ms after trigger, i.e. when CereStim 14177 is used and wait(100) function present, the stimulation occurs at correct time, with a slight delay of 300 us.

%Used Matlab code to send pulse on CereStim 14177 (the CereStim that was
%sent back to BR and that Saman reprogrammed), minus the first pairs of 'trigger' pulses. No wait() command used. 
%Recorded sync pulse output from 14177, on analog input 13.
date='041017_test_microstim_waveform6';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:),'b');
plot(NSch(16,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(13,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=65344;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000

%Used Matlab code to send pulse on CereStim 14293 (the CereStim that was
%sent back to BR and that Saman reprogrammed), minus the first pairs of 'trigger' pulses. No wait() command used. 
%Recorded sync pulse output from 14177, on analog input 13.
date='041017_test_microstim_waveform7';
instanceInd=2;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:),'b');
plot(NSch(16,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(13,:),'c');%plot signal on analog input 13, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=65344;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000

%Used Matlab code to send pulse on CereStim 14173, using runstim_microstim_saccade_catch25.m code.
%Checked condiiton: LRorTB=1 & targetLocation=2, where microstimulation
%supposed to be sent on electrodes 8 and 51 on array 10. Connected modified MIT cable
%to bank B of CereStim (i.e. channels 33 to 64) and connected probe across
%45-kOhm resister corresponding to channel 51 (51 - 32 = 19), i.e.
%connected acoss resistor number 19. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim on analog input
%7, and copy of trigger pulse on analog input 16.
%Recorded sync pulse output from 14173, on analog input 7.
%Note that voltage reached saturation slightly.
date='051017_test_microstim_waveform1';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000

%Used Matlab code to send pulse on CereStim 14173, using runstim_microstim_saccade_catch25.m code.
%Checked condiiton: LRorTB=1 & targetLocation=2, where microstimulation
%supposed to be sent on electrodes 8 and 51 on array 10. Connected modified MIT cable
%to bank A of CereStim (i.e. channels 1 to 32) and connected probe across
%45-kOhm resister corresponding to channel 8, i.e.
%connected acoss resistor number 8. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim on analog input
%7, and copy of trigger pulse on analog input 16.
%Recorded sync pulse output from 14173, on analog input 7.
%Note that voltage reached saturation slightly.
date='051017_test_microstim_waveform2';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000

%Used Matlab code to send pulse on CereStims 14176 & 14173, using runstim_microstim_saccade_catch25.m code.
%Checked condiiton: LRorTB=1 & targetLocation=1, where microstimulation
%supposed to be sent on electrodes 49 and 51 on arrays 13 and 10 respectively. Connected modified MIT cable
%to bank B of CereStim 14176 (i.e. channels 33 to 64) and connected probe across
%45-kOhm resister corresponding to channel 49, i.e.
%connected acoss resistor number 17. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim on analog input
%7, and copy of trigger pulse on analog input 16.
%Recorded sync pulse output from 14176, on analog input 10.
date='051017_test_microstim_waveform3';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 10, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0002 s = 0.2 ms = 200 us

%Used Matlab code to send pulse on CereStims 14176 & 14173, using runstim_microstim_saccade_catch25.m code.
%Checked condiiton: LRorTB=1 & targetLocation=1, where microstimulation
%supposed to be sent on electrodes 49 and 51 on arrays 13 and 10 respectively. Connected modified MIT cable
%to bank B of CereStim 14173 (i.e. channels 33 to 64) and connected probe across
%45-kOhm resister corresponding to channel 51, i.e.
%connected acoss resistor number 19. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim on analog input
%7, and copy of trigger pulse on analog input 16.
%Recorded sync pulse output from 14173, on analog input 7.
date='051017_test_microstim_waveform4';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0006 s = 0.6 ms = 600 us

%Used Matlab code to send pulse on CereStims 14176 & 14173, using runstim_microstim_saccade_catch25.m code.
%Checked condiiton: LRorTB=2 & targetLocation=1, where microstimulation
%supposed to be sent on electrodes 49 and 8 on arrays 13 and 10 respectively. Connected modified MIT cable
%to bank A of CereStim 14173 (i.e. channels 1 to 32) and connected probe across
%45-kOhm resister corresponding to channel 8, i.e.
%connected acoss resistor number 8. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim on analog input
%7, and copy of trigger pulse on analog input 16.
%Recorded sync pulse output from 14173, on analog input 7.
date='051017_test_microstim_waveform5';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0006 s = 0.6 ms = 600 us

%Used Matlab code to send pulse on CereStims 14176 & 14173, using runstim_microstim_saccade_catch25.m code.
%Checked condiiton: LRorTB=2 & targetLocation=1, where microstimulation
%supposed to be sent on electrodes 49 and 8 on arrays 13 and 10 respectively. Connected modified MIT cable
%to bank B of CereStim 14176 (i.e. channels 33 to 64) and connected probe across
%45-kOhm resister corresponding to channel 49, i.e.
%connected acoss resistor number 17. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim on analog input
%10, and copy of trigger pulse on analog input 16.
%Recorded sync pulse output from 14176, on analog input 10.
date='051017_test_microstim_waveform6';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0006 s = 0.6 ms = 600 us

%Used Matlab code to send pulse on CereStims 14176 & 14173, using runstim_microstim_saccade_catch25.m code.
%Checked condiiton: LRorTB=2 & targetLocation=1, where microstimulation
%supposed to be sent on electrodes 49 and 8 on arrays 13 and 10 respectively. Connected modified MIT cable
%to bank A of CereStim 14173 (i.e. channels 1 to 32) and connected probe across
%45-kOhm resister corresponding to channel 8, i.e.
%connected acoss resistor number 8. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim 14173 on analog input
%7, and copy of trigger pulse on analog input 16.
date='051017_test_microstim_waveform7';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0006 s = 0.6 ms = 600 us

%Used Matlab code to send pulse on CereStims 14176 & 14173, using runstim_microstim_saccade_catch25.m code.
%Checked condiiton: LRorTB=2 & targetLocation=2, where microstimulation
%supposed to be sent on electrodes 49 and 8 on arrays 13 and 10 respectively. Connected modified MIT cable
%to bank B of CereStim 14176 (i.e. channels 33 to 64) and connected probe across
%45-kOhm resister corresponding to channel 37, i.e.
%connected acoss resistor number 5. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim 14176 on analog input
%10, and copy of trigger pulse on analog input 16.
date='051017_test_microstim_waveform8';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0006 s = 0.6 ms = 600 us

%Used Matlab code to send pulse on CereStims 14176 & 14173, using runstim_microstim_saccade_catch25.m code.
%Checked condiiton: LRorTB=2 & targetLocation=2, where microstimulation
%supposed to be sent on electrodes 49 and 8 on arrays 13 and 10 respectively. Connected modified MIT cable
%to bank B of CereStim 14173 (i.e. channels 33 to 64) and connected probe across
%45-kOhm resister corresponding to channel 51, i.e.
%connected acoss resistor number 19. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim 14176 on analog input
%7, and copy of trigger pulse on analog input 16.
date='051017_test_microstim_waveform9';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0006 s = 0.6 ms = 600 us

%Used Matlab code to send pulse on new set of 4 electrodes.
%CereStims 14175 & 14173, using runstim_microstim_saccade_catch27.m code.
%Checked condiiton: LRorTB=1 & targetLocation=1, where microstimulation
%supposed to be sent on electrodes 29 and 40 on arrays 12 and 10 respectively. Connected modified MIT cable
%to bank A of CereStim 14176 (i.e. channels 1 to 32) and connected probe across
%45-kOhm resister corresponding to channel 29, i.e.
%connected acoss resistor number 29. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim 14175 on analog input
%7, and copy of trigger pulse on analog input 16.
date='061017_test_microstim_waveform1';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000

%Used Matlab code to send pulse on new set of 4 electrodes.
%CereStims 14175 & 14173, using runstim_microstim_saccade_catch27.m code.
%Checked condiiton: LRorTB=1 & targetLocation=1, where microstimulation
%supposed to be sent on electrodes 29 and 40 on arrays 12 and 10 respectively. Connected modified MIT cable
%to bank B of CereStim 14173 (i.e. channels 33 to 64) and connected probe across
%45-kOhm resister corresponding to channel 40, i.e.
%connected acoss resistor number 8. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim 14173 on analog input
%7, and copy of trigger pulse on analog input 16.
date='061017_test_microstim_waveform2';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0054 s = 5.4 ms

%Used Matlab code to send pulse on new set of 4 electrodes.
%CereStims 14175 & 14173, using runstim_microstim_saccade_catch27.m code.
%Checked condiiton: LRorTB=1 & targetLocation=2, where microstimulation
%supposed to be sent on electrodes 38 and 40 on arrays 13 and 10 respectively. Connected modified MIT cable
%to bank B of CereStim 14173 (i.e. channels 33 to 64) and connected probe across
%45-kOhm resister corresponding to channel 40, i.e.
%connected acoss resistor number 8. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim 14173 on analog input
%7, and copy of trigger pulse on analog input 16.
date='061017_test_microstim_waveform3';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0056 s = 5.6 ms

%Used Matlab code to send pulse on new set of 4 electrodes.
%CereStims 14175 & 14173, using runstim_microstim_saccade_catch27.m code.
%Checked condiiton: LRorTB=1 & targetLocation=2, where microstimulation
%supposed to be sent on electrodes 38 and 40 on arrays 13 and 10 respectively. Connected modified MIT cable
%to bank B of CereStim 14176 (i.e. channels 33 to 64) and connected probe across
%45-kOhm resister corresponding to channel 38, i.e.
%connected acoss resistor number 6. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim 14176 on analog input
%10, and copy of trigger pulse on analog input 16.
date='061017_test_microstim_waveform4';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0051 s = 5.1 ms

%Used Matlab code to send pulse on new set of 4 electrodes.
%CereStims 14175 & 14173, using runstim_microstim_saccade_catch27.m code.
%Checked condiiton: LRorTB=2 & targetLocation=1, where microstimulation
%supposed to be sent on electrodes 38 and 29 on arrays 13 and 12 respectively. Connected modified MIT cable
%to bank B of CereStim 14176 (i.e. channels 33 to 64) and connected probe across
%45-kOhm resister corresponding to channel 38, i.e.
%connected acoss resistor number 6. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim 14176 on analog input
%10, and copy of trigger pulse on analog input 16.
date='061017_test_microstim_waveform5';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0072 s = 7.2 ms

%Used Matlab code to send pulse on new set of 4 electrodes.
%CereStims 14175 & 14173, using runstim_microstim_saccade_catch27.m code.
%Checked condiiton: LRorTB=2 & targetLocation=1, where microstimulation
%supposed to be sent on electrodes 38 and 29 on arrays 13 and 12 respectively. Connected modified MIT cable
%to bank A of CereStim 14175 (i.e. channels 1 to 32) and connected probe across
%45-kOhm resister corresponding to channel 29, i.e.
%connected acoss resistor number 29. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim 14175 on analog input
%9, and copy of trigger pulse on analog input 16.
date='061017_test_microstim_waveform6';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0095 s = 9.5 ms

%Used Matlab code to send pulse on new set of 4 electrodes.
%CereStims 14293 & 14173, using runstim_microstim_saccade_catch27.m code.
%Checked condiiton: LRorTB=2 & targetLocation=2, where microstimulation
%supposed to be sent on electrodes 62 and 40 on arrays 15 and 10 respectively. Connected modified MIT cable
%to bank B of CereStim 14175 (i.e. channels 33 to 64) and connected probe across
%45-kOhm resister corresponding to channel 62, i.e.
%connected acoss resistor number 30. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim 14293 on analog input
%12, and copy of trigger pulse on analog input 16.
date='061017_test_microstim_waveform7';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0008 s = 0.8 ms

%Used Matlab code to send pulse on new set of 4 electrodes.
%CereStims 14293 & 14173, using runstim_microstim_saccade_catch27.m code.
%Checked condiiton: LRorTB=2 & targetLocation=2, where microstimulation
%supposed to be sent on electrodes 62 and 40 on arrays 15 and 10 respectively. Connected modified MIT cable
%to bank B of CereStim 14173 (i.e. channels 33 to 64) and connected probe across
%45-kOhm resister corresponding to channel 40, i.e.
%connected acoss resistor number 8. Sent output via BNC cable to analog
%input 15. Simultaneously recorded sync pulse from CereStim 14173 on analog input
%12, and copy of trigger pulse on analog input 16.
date='061017_test_microstim_waveform8';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(2,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(1,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0005 s = 0.5 ms

%Used Matlab code to send pulse on test pair of electrodes, on same CereStim, with wait(50).
%CereStim 14293, using runstim_microstim_test_waveform3.m code. 10 pulses.
%anodic first on one electrode, cathodic first on the other.
%Connected normal MIT cable to Y adaptor on NSS, and connected CerePlex M
%to Y adapter, sending input to instance 1.
%Simultaneously recorded sync pulse from CereStim 14293 on analog input
%12, and copy of trigger pulse on analog input 14.
date='101017_test_microstim_waveform';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(2,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0005 s = 0.5 ms

%Used Matlab code to send pulse on test pair of electrodes, on same CereStim, with wait(50).
%CereStim 14293, using runstim_microstim_test_waveform3.m code. 1 pulse.
%Connected normal MIT cable to Y adaptor on NSS, and connected CerePlex M
%to Y adapter, sending input to instance 1.
%Simultaneously recorded sync pulse from CereStim 14293 on analog input
%12, and copy of trigger pulse on analog input 14.
date='101017_test_microstim_waveform2';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(2,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0032 s = 3.2 ms?

%Used Matlab code to send pulse on test pair of electrodes, on same CereStim, with wait(200).
%CereStim 14293, using runstim_microstim_test_waveform3.m code. 1 pulse.
%Connected normal MIT cable to Y adaptor on NSS, and connected CerePlex M
%to Y adapter, sending input to instance 1.
%Simultaneously recorded sync pulse from CereStim 14293 on analog input
%12, and copy of trigger pulse on analog input 14.
date='101017_test_microstim_waveform3';
instanceInd=1;
instanceName=['instance',num2str(instanceInd)];
instanceNEVFileName=['D:\data\',date,'\',instanceName,'.nev'];
NEV=openNEV(instanceNEVFileName);
instanceNS6FileName=['D:\data\',date,'\',instanceName,'.ns6'];
NSchOriginal=openNSx(instanceNS6FileName);
NSch=NSchOriginal.Data;
figure;hold on
plot(NSch(1,:),'b');
plot(NSch(3,:),'m');%plot signal on analog input 16, indicates timing of dasbit for trigger
plot(NSch(2,:),'c');%plot signal on analog input 7, which shows sync pulse from second CereStim
ylimits=get(gca,'ylim');
microB=6;
microBTimestamps=find(NEV.Data.SerialDigitalIO.UnparsedData==2^microB);
for i=1:length(microBTimestamps)
    plot([NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i)) NEV.Data.SerialDigitalIO.TimeStamp(microBTimestamps(i))],ylimits,'r:');
end
(cursor_info.Position(1) - cursor_info2.Position(1))/30000
%delay: 0.0033 s = 3.3 ms?
